import {Platform} from 'react-native';

export const theme = {
  colors: {
    primary: '#3498db',
    secondary: '#2ecc71',
    white: '#FFFFFF',
    black: '#000000',
    darker: '#121212',
    lighter: '#F3F3F3',
    background: '#1A1A2E',
    cardBackground: '#2B2B3D',
    accent: '#39FF14',
    danger: '#FF6347',
    textPrimary: '#FFF',
    textSecondary: '#A9A9A9',
    borderColor: '#ddd',
    inputBackground: '#f9f9f9',
  },
  typography: Platform.select({
    ios: {
      fontFamily: 'Arial',
      fontSize: 16,
    },
    android: {
      fontFamily: 'Roboto',
      fontSize: 18,
    },
  }),
  fontSizes: {
    title: 22,
    subtitle: 18,
    body: 16,
  },
  spacing: {
    small: 8,
    medium: 16,
    large: 20,
  },
  borderRadius: {
    small: 8,
    medium: 12,
    large: 25,
  },
  shadows: Platform.select({
    ios: {
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    android: {
      elevation: 4,
    },
  }),
  headerStyles: {
    headerTitleAlign: 'center',
    headerStyle: {
      backgroundColor: '#1A1A2E',
      height: Platform.OS === 'ios' ? 100 : 70,
    },
    headerTitleStyle: {
      fontWeight: 'bold',
      fontSize: Platform.OS === 'ios' ? 20 : 18,
      fontFamily: Platform.OS === 'ios' ? 'Arial' : 'Roboto',
      color: '#FFF',
    },
    headerTintColor: '#FFF', 
  },
  characterListStyles: {
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: '#1A1A2E',
    },
    searchInput: {
      height: 50,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 25,
      paddingHorizontal: 20,
      fontSize: 18,
      backgroundColor: '#f9f9f9',
      alignSelf: 'center',
      width: '90%',
      textAlign: 'center',
    },
    errorText: {
      color: '#FF6347',
      textAlign: 'center',
      marginVertical: 10,
    },
    noResultsText: {
      color: '#FFF',
      textAlign: 'center',
      fontSize: 18,
      marginTop: 20,
    },
    paginationBar: {
      position: 'absolute',
      bottom: 20,
      left: 30,
      right: 30,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: '#1A1A2E',
      padding: 8,
      borderRadius: 8,
      elevation: 4,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.7,
      shadowRadius: 2,
    },
    pageNumber: {
      color: '#FFF',
      fontSize: 16,
    },
  },
  characterDetailStyles: {
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#1A1A2E',
    },
    image: {
      width: 180,
      height: 180,
      borderRadius: 90,
      marginBottom: 20,
      borderWidth: 4,
      borderColor: '#39FF14',
    },
    infoContainer: {
      backgroundColor: '#2B2B3D',
      borderRadius: 12,
      padding: 20,
      width: '90%',
      alignItems: 'center',
      marginTop: 20,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.7,
      shadowRadius: 2,
    },
    name: {
      fontSize: 26,
      fontWeight: 'bold',
      color: '#FFF',
      marginBottom: 16,
      textAlign: 'center',
    },
    details: {
      flexDirection: 'row',
      marginVertical: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    label: {
      fontSize: 18,
      color: '#A9A9A9',
      fontWeight: '600',
      marginRight: 4,
    },
    value: {
      fontSize: 18,
      color: '#FFF',
      fontWeight: '400',
    },
    favoriteButton: {
      marginTop: 20,
      backgroundColor: '#39FF14',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 8,
    },
    favoriteButtonText: {
      fontSize: 16,
      color: '#1A1A2E',
      fontWeight: '600',
    },
    disabledButton: {
      backgroundColor: '#A9A9A9',
    },
    toast: {
      position: 'absolute',
      bottom: 100,
      backgroundColor: '#39FF14',
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 8,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.5,
      shadowRadius: 5,
    },
    toastText: {
      color: '#1A1A2E',
      fontSize: 16,
      fontWeight: 'bold',
    },
  },
  characterCardStyles: {
    card: {
      backgroundColor: '#39FF14',
      borderRadius: 12,
      padding: 16,
      marginVertical: 10,
      alignItems: 'center',
    },
    cardContent: {
      alignItems: 'center',
    },
    image: {
      width: 80,
      height: 80,
      borderRadius: 40,
      marginBottom: 10,
    },
    name: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#1A1A2E',
    },
    favoriteButton: {
      marginTop: 10,
      backgroundColor: '#1A1A2E',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 25,
      borderWidth: 2,
      borderColor: '#39FF14',
      shadowColor: '#00FF00',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.8,
      shadowRadius: 4,
      alignItems: 'center',
    },
    favoriteButtonText: {
      fontSize: 14,
      color: '#39FF14',
      fontWeight: 'bold',
    },
    disabledButton: {
      backgroundColor: '#333333',
      borderColor: '#A9A9A9',
    },
  },
  favoritesScreenStyles: {
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: '#1A1A2E',
    },
    card: {
      backgroundColor: '#2B2B3D',
      borderRadius: 12,
      padding: 16,
      marginVertical: 8,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.3,
      shadowRadius: 4,
    },
    name: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#39FF14',
      marginBottom: 8,
      textAlign: 'center',
    },
    details: {
      fontSize: 16,
      color: '#FFF',
      textAlign: 'center',
      marginBottom: 4,
    },
    removeButton: {
      backgroundColor: '#FF6347',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      alignItems: 'center',
      marginTop: 8,
    },
    removeButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
    },
    noFavoritesText: {
      color: '#FFF',
      fontSize: 18,
      textAlign: 'center',
      marginTop: 20,
    },
  },
};
